### PR TITLE
Updated readme and plugin.json

### PR DESCRIPTION
**Pull request by hydra45**
I'm an intern at Vector35, and I made some changes to your README and plugin.json files. I added another screenshot to the README and longdescription field in plugin.json, in addition to adjusted longdescription to display images in readme.

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks for the PR. I'm not sure if the new screenshot is useful--it just shows the architecture's name, which is the same as the plugin's.

**Comment by psifertex** [comment]
The screenshot itself is definitely not necessary. 

The part that /would/ be nice though is if the `longdescription` in the plugin.json contained more of the info in the readme.md (indeed, if you use the generator scripts in the example repo they can make the entire readme.md from the components of the json).

The main benefit is that that would show people using the built-in plugin manager the screenshot and more information in the UI. 

I'll ask Will to redo the PR to use the existing SS since I agree that makes more sense.

**Comment by whitequark** [comment]
Cool! I never really figured out how to get the scripts to work.

**Comment by psifertex** [comment]
No worries, easy enough to amend this to remove the extra image. Will's currently working on some type library stuff but as soon as he's done with that he'll be back to helping improve readmes.

**Comment by whitequark** [comment]
It's been a few months with no changes so I'm closing this--let me know if you'd like to finish those changes and I can reopen.

**Pull request closed without merging**
